<template><div><h1 id="nodejs" tabindex="-1"><a class="header-anchor" href="#nodejs"><span>Nodejs</span></a></h1>
<p>How to install ?</p>
<div class="language-npm line-numbers-mode" data-highlighter="prismjs" data-ext="npm" data-title="npm"><pre v-pre><code><span class="line">npm i tg-bot-sender</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="imports" tabindex="-1"><a class="header-anchor" href="#imports"><span>Imports</span></a></h2>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> TelegaSender<span class="token punctuation">,</span> Methods<span class="token punctuation">,</span> Data <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"tg-bot-sender"</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>The structure of the Data message</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text" data-title="text"><pre v-pre><code><span class="line">type Data = {</span>
<span class="line">    text: string,</span>
<span class="line">    photo?: string,</span>
<span class="line">    buttons?: {</span>
<span class="line">        buttonTitle: string,</span>
<span class="line">        buttonUrl: string</span>
<span class="line">    }[]</span>
<span class="line">}</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Response structure</p>
<div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json" data-title="json"><pre v-pre><code><span class="line"><span class="token punctuation">{</span> <span class="token property">"amount"</span><span class="token operator">:</span> <span class="token number">0</span> <span class="token punctuation">}</span> <span class="token comment">// number of messages sent</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="getting-started" tabindex="-1"><a class="header-anchor" href="#getting-started"><span>Getting started</span></a></h2>
<p>The logs parameter indicates that logs are saved in json format</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">const</span> tg <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TelegaSender</span><span class="token punctuation">(</span>telegramToken<span class="token punctuation">,</span> pathForLogs<span class="token punctuation">,</span> logs <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="options-for-sending-messages" tabindex="-1"><a class="header-anchor" href="#options-for-sending-messages"><span>Options for sending messages</span></a></h2>
<p>Sending photos</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">Methods<span class="token punctuation">.</span>sendPhoto</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="sendfromids-sending-to-users" tabindex="-1"><a class="header-anchor" href="#sendfromids-sending-to-users"><span>sendFromIds - sending to users</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token operator">...</span>telegramUserIds<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    photo<span class="token operator">:</span> <span class="token string">'Photo link'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="sendfromid-sending-to-the-user" tabindex="-1"><a class="header-anchor" href="#sendfromid-sending-to-the-user"><span>sendFromId - sending to the user</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span>telegramUserId<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    photo<span class="token operator">:</span> <span class="token string">'Photo link'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Sending a message</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">Methods<span class="token punctuation">.</span>sendMessage</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="sendfromids-sending-to-users-1" tabindex="-1"><a class="header-anchor" href="#sendfromids-sending-to-users-1"><span>sendFromIds - sending to users</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token operator">...</span>telegramUserIds<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendMessage<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="sendfromid-sending-to-the-user-1" tabindex="-1"><a class="header-anchor" href="#sendfromid-sending-to-the-user-1"><span>sendFromId - sending to the user</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span>telegramUserId<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


