<template><div><h1 id="документация" tabindex="-1"><a class="header-anchor" href="#документация"><span>Документация</span></a></h1>
<p>Как установить ?</p>
<div class="language-npm line-numbers-mode" data-highlighter="prismjs" data-ext="npm" data-title="npm"><pre v-pre><code><span class="line">npm i tg-bot-sender</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="импорты" tabindex="-1"><a class="header-anchor" href="#импорты"><span>Импорты</span></a></h2>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> TelegaSender<span class="token punctuation">,</span> Methods <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"tg-bot-sender"</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="начало-работы" tabindex="-1"><a class="header-anchor" href="#начало-работы"><span>Начало работы</span></a></h2>
<p>logs параметр указывает на сохранения логов в json формате</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">const</span> tg <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TelegaSender</span><span class="token punctuation">(</span>telegramToken<span class="token punctuation">,</span> pathForLogs<span class="token punctuation">,</span> logs <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="варианты-отправки-сообщении" tabindex="-1"><a class="header-anchor" href="#варианты-отправки-сообщении"><span>Варианты отправки сообщений</span></a></h2>
<p>Отправка фото</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">Methods<span class="token punctuation">.</span>sendPhoto</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="sendfromids-отправка-пользователям" tabindex="-1"><a class="header-anchor" href="#sendfromids-отправка-пользователям"><span>sendFromIds - отправка пользователям</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token operator">...</span>telegramUserIds<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    photo<span class="token operator">:</span> <span class="token string">'Photo link'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="sendfromid-отправка-пользователю" tabindex="-1"><a class="header-anchor" href="#sendfromid-отправка-пользователю"><span>sendFromId - отправка пользователю</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span>telegramUserId<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    photo<span class="token operator">:</span> <span class="token string">'Photo link'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Отправка сообщения</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">Methods<span class="token punctuation">.</span>sendMessage</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="sendfromids-отправка-пользователям-1" tabindex="-1"><a class="header-anchor" href="#sendfromids-отправка-пользователям-1"><span>sendFromIds - отправка пользователям</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token operator">...</span>telegramUserIds<span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendMessage<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="sendfromid-отправка-пользователю-1" tabindex="-1"><a class="header-anchor" href="#sendfromid-отправка-пользователю-1"><span>sendFromId - отправка пользователю</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line">tg<span class="token punctuation">.</span><span class="token function">sendFromIds</span><span class="token punctuation">(</span>telegramUserId<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">    text<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">    buttons<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">{</span></span>
<span class="line">        buttonTitle<span class="token operator">:</span> <span class="token string">'Hello'</span><span class="token punctuation">,</span></span>
<span class="line">        buttonUrl<span class="token operator">:</span> <span class="token string">'https://google.com'</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">]</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">,</span> Methods<span class="token punctuation">.</span>sendPhoto<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>res<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>res<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span>err<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


